DROP TABLE IF EXISTS WORDS;
DROP TABLE IF EXISTS SUBARTICLES;

CREATE TABLE IF NOT EXISTS WORDS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    article MEDIUMTEXT,
    INDEX (name)
);

CREATE TABLE IF NOT EXISTS SUBARTICLES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    word_id INTEGER NOT NULL,
    parent_id INTEGER,
    level SMALLINT,
    article MEDIUMTEXT,
    CONSTRAINT FK_WORD FOREIGN KEY (word_id) REFERENCES WORDS(id),
    CONSTRAINT FK_PARENT FOREIGN KEY (parent_id) REFERENCES SUBARTICLES(id)
);
