spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/longman?serverTimezone=UTC
        username: root
        password: e4e5Kc3Kf6

    thymeleaf:
        cache: false

logging:
    level:
        org.springframework.jdbc.core.JdbcTemplate: TRACE

